### ISSUE TITLE
after install this error

### ISSUE THREAD

**Issue by yamcell** [FirezYT/xtream-codes-nulled#1]
Connect Error: Connection refused

**Comment by FirezYT** [comment]
What VPS service did you use?

**Comment by devbilgin** [comment]
hi , is only setup 14.04 lts ?

can we setup other version ?

**Comment by FirezYT** [comment]
Only 14.04 and use my new repository that works. https://github.com/FirezYT/xtream-codes-fixed/

**Comment by devbilgin** [comment]
https://i.imgyukle.com/2019/09/27/o4kYII.jpg

more this error , why ?
